### ISSUE TITLE
Does not support users who type in Japanese

### ISSUE THREAD

**Issue by PeterTakahashi** [mckaywrigley/chatbot-ui-pro#3]
# bug
The Japanese language has both kanji and hiragana, and the enter key is used to convert hiragana into kanji.
In the current implementation, `handleSend` is executed when the conversion is confirmed and starts sending messages.

# solution
When the conversion key is pressed, the message is not sent.

![スクリーンショット 2023-03-18 8 30 03](https://user-images.githubusercontent.com/40238917/226069406-94498d43-ae42-4c4d-9bb2-0e4d2c6a9126.png)

**Comment by mckaywrigley** [comment]
Merged!
